---
- name: "Install Grafana Alloy from binary"
  ansible.builtin.include_tasks: install.yml

- name: "Configure Alloy"
  ansible.builtin.include_tasks: configure.yml

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"
